### ISSUE TITLE
after playing with this mod for a month (i have 700 hour in game)

### ISSUE THREAD

**Issue by piyason** [fireundubh/fo4-mods#11]
sry if my english not good . this is very good mod i thank you very much you made this

for me i have some problem when enable mod and i loot some container/body by myself
the game is freeze (when crosshair over body or container and it say "press E")but it look random for me 
i have know idea why this happen. 

i play with this mod and almost wipe out the wasteland (take everything / set respawn cell to mult 1000)
some of my save i dont got any issue anymore

i try to use only this mod and it very stable (i use only 8192)
i am learn to mod by myself too i think im sure i dont do anything wrong (i almost play with this mod only lol)

anyway thank you for this you are my hero!!

**Comment by fireundubh** [comment]
I can't explain your freeze issue. Auto Loot does what you already can do faster, so there is no way for the mod to cause freezes unless there's a problem with the game itself.

**Comment by piyason** [comment]
this freeze happen often if i install the mod before leave vault111. maybe this freeze is because quest bugs(auto loot is quest?)?

anyway thank for your reply xD the mod is perfect anyway for me

**Comment by fireundubh** [comment]
Please deactivate all modules, uninstall the mod, and install the latest version.

Create a new issue if you experience further lockups.

**Comment by fortunequacker** [comment]
OP - "for me i have some problem when enable mod and i loot some container/body by myself
the game is freeze (when crosshair over body or container and it say "press E")but it look random for me"

This is what I too am experiencing.  Only it is not random.  If I "mouse over" a body, whether it has content or not, my game freezes.  I have to kill the process in Task Manager.  I have the latest version downloaded from GitHub with filters for bodies, containers, flora, and junk active.  I have the destination container set to the player for all items.  This is very consistent.  I restarted and tried it three times on the same container "a small toolbox" and three times on flora "a hubi flower".

**Comment by fireundubh** [comment]
Nothing to do with Auto Loot.
