### ISSUE TITLE
auto loot request

### ISSUE THREAD

**Issue by prayoga-masagi** [fireundubh/fo4-mods#14]
can you replace the auto steal module with "setownership" to player,
so you literally can loot all item without everybody shooting at you.

by the way,  any change using this mod in survival mode latest patch?
thanks, sorry for my bad English

**Comment by fireundubh** [comment]
You can already loot all items without everybody shooting at you. Hide!

Auto Steal should be used situationally, so you:

1. Find a place to hide.
2. Turn on Auto Steal.
3. Wait.
4. Turn off Auto Steal.
5. Leave your hiding place.

No change for Survival Mode.

**Comment by prayoga-masagi** [comment]
ok, thanks, i will closed this issue

**Comment by fireundubh** [comment]
By the way, I did add a feature awhile ago that allows you to toggle whether auto steal triggers combat.
