### ISSUE TITLE
Auto Loot Broken with v1.5.147.0

### ISSUE THREAD

**Issue by icdmize** [fireundubh/fo4-mods#15]
The holotape has disappeared and uninstalling and reinstalling does nothing.  The script is no longer running.

**Comment by phuhque** [comment]
Are you by chance running Hardcore?

**Comment by fireundubh** [comment]
You'll have to add the holotape manually with the console.

**Comment by icdmize** [comment]
How do I go about doing this?  player.additem "?"  I'm not having any luck finding the reference id.  Thanks for this great mod and your assistance by the way.

**Comment by fireundubh** [comment]
If you enter `help "auto loot" 4`, you can find the Form ID for the Auto Loot Program.
