### ISSUE TITLE
Only ammo filter works.

### ISSUE THREAD

**Issue by jrubimf** [fireundubh/fo4-mods#16]
Reinstalled mod from both Github and Mod menu.

**Comment by fireundubh** [comment]
All filters work here. I thoroughly tested the mod before releasing.

The Ammo and Medicine filters have, by default, their containers set to the player only, while other filters can, by default, send loot to the player or settlement. If you have a non-player container set for all filters or the other filters, loot will be delivered to those containers silently. You will not receive any notifications when a non-player container is used.

**Comment by jrubimf** [comment]
Medicines are not working.

Will try a clean Fallout 4 install. If you want it, i can make a video.

**Comment by fireundubh** [comment]
All filters except Bodies and Containers use the same script and exactly the same setup, so if one fails, all must fail.

If you were using the previous version of Auto Loot, did you turn off all filters before installing the new version?

**Comment by fireundubh** [comment]
Version 3 has been uploaded to Bethesda.net. Only the source files will be available on GitHub going forward.

Please let me know if Version 3 resolves your issue.

**Comment by jrubimf** [comment]
Got it.

Here's the video: https://www.youtube.com/watch?v=X9DJOI11rOQ

Fond out something, this "bug" only happens on containers and bodies. Autoloot is still picking up items from the ground.

**Comment by fireundubh** [comment]
I found it. The pre-CK mod was working perfectly. I'll have an update up shortly. /sigh

**Comment by jrubimf** [comment]
Thx for the heads up!

**Comment by jrubimf** [comment]
Still same issue. Sight.

**Comment by fireundubh** [comment]
It can't happen programmatically, so I don't know what's wrong with your game.
