### ISSUE TITLE
Download dosen't work

### ISSUE THREAD

**Issue by JacobNielsenn** [fireundubh/fo4-mods#17]
Trying to download the esp and ba2 file results in Page not found error (404)

**Comment by fireundubh** [comment]
If you're trying to download Auto Loot from GitHub, it has been moved to Bethesda.net.

**Comment by phuhque** [comment]
Do you by chance have a link to your mod over there?  I will have to down load it while at work because my on computer the forced requirement of java without prompting is impossible for me to actually get to.  I haven't uninstalled java yet but am damned close to doing so. I have already uninstalled flash due to all the vulnerabilities it has.

**Comment by fireundubh** [comment]
Here is the mod page: [https://mods.bethesda.net/#en/workshop/fallout4/mod-detail/758870](https://mods.bethesda.net/#en/workshop/fallout4/mod-detail/758870)

**Comment by phuhque** [comment]
I will have to try it from work.  I guess to get mods from there bethesda you are required to have an account, which I cannot even create from home.

At some point, hopefully you will get your mods on Nexus or Steam.  Thanks for the link though.  It should be quick once I get in tomorrow.

**Comment by phuhque** [comment]
Found out the mods can't actually be downloaded.  The only way to use them is if you have an active internet connection.  One of the security setting somewhere on my firewall prevents me from using the new Bethesda DRM feature.  Hopefully someone will release a similar mod on Nexus or steam.  Bethesda, it seems, is requiring some connection that my security just won't play with.  Thanks anyway.

**Comment by DrWolfnstine** [comment]
I am having the same issue as phuhque with Bethesda's new DRM feature, I think it may be my routers firewall, not sure. Do you have any plans to upload this to the nexus with an NMM installer?

**Comment by DrWolfnstine** [comment]
Update: I was able to get it work, it was my router firewall, phuhque try adding an exception if you have access. It worked for me. I would still love to see this mod on nexus though.

**Comment by phuhque** [comment]
Actually, found it it had nothing at all to do with my firewall.  SweetFX launching was blocking it AND causing CTD's.  What I have done is download his mod in Bethesda.  Exit the game.  Zip up anything that changed that instant, then load it into NMM and activate.There are a couple of mods I have done that with for Authors who aren't uploading to Nexus.  Will do the same to any steam mods that come up.  Thanks though.  I knew it wasn't my firewall as there were never any DNS lookups at all being generated.

**Comment by DrWolfnstine** [comment]
I'm glad you were able to fix it, leave it NMM to make it work for you.

**Comment by fireundubh** [comment]
I don't support the Nexus. None of my mods will ever be uploaded there again.

**Comment by fireundubh** [comment]
To all, you can download all mods from GitHub once again, and this time, you can use a more accessible website:

[http://fireundubh.github.io/fallout4/](http://fireundubh.github.io/fallout4/)
