### ISSUE TITLE
Autoloot misses things a lot

### ISSUE THREAD

**Issue by darrel343** [fireundubh/fo4-mods#2]
Using filter mode with all modules activated, seems to happen regardless of radius. Containers and dead bodies don't get looted. I noticed Nuclear Material, .45 ammo, Dirty Water, so it happens with items from all categories. 

It gets plants and flowers from the environment reliably, but seems peculiar and inconsistent with containers and especially with dead bodies. It will often pick up mirelurk meat from one out of three dead mirelurks, pick up ammo from one out of five dead raiders, loot one container according to my filters and leave another untouched etcetera. I understand that it doesn't loot owned items, but don't really understand why so many items aren't getting picked up by it.

**Comment by fireundubh** [comment]
Every object that isn't looted is actually already in the formlists, but some objects are not picked up for whatever reason. The behavior is erratic. For example, in the trailer outside Vault 111, there's a Desk Fan, Cram, a few cups and a pitcher, a bottlecap, 10mm Ammo, and a Switchblade. Everything in that trailer except the Switchblade should be auto looted, but only one, a few, or none have been auto looted in my many, many tests.
 
Only SmkViper [Bethesda game programmer and Papyrus lead] could tell me what's happening behind the scenes in the game engine; however, mods aren't officially supported by Bethesda, so we'll have to wait for the toolset before we can make use of his expertise.

**Comment by gendalv** [comment]
I have the same thing, random things pretty much everywhere have to be looted manually.

**Comment by fireundubh** [comment]
As above, there is nothing that can be done.
