### ISSUE TITLE
bobby pins package

### ISSUE THREAD

**Issue by gendalv** [fireundubh/fo4-mods#3]
bobby pins package/box (or whatever it's name in english), is picked up as a box instead of pins - you can't pick up a box in vanila - it automatically gives multiple bobby pins instead (kinda like a box of caps), but this mod picks up the box.

**Comment by fireundubh** [comment]
```
Bool Function Activate(ObjectReference akActivator, Bool abDefaultProcessingOnly = False) native
```

To prevent errors, `abDefaultProcessingOnly` is set to `True`. Auto Loot therefore does not trigger the OnActivate event. For objects that execute a script when activated, turn off the respective Auto Loot module, drop the object, and activate the object manually.
