### ISSUE TITLE
Auto Loot does not work on a brand new game.

### ISSUE THREAD

**Issue by clampi** [fireundubh/fo4-mods#5]
Description/How to reproduce:
Although the configuration-holotape is given immediately after face-cofiguration is finished, it does not persist through the pre-war era and freeze :p . (latest version of mod used)

Expected result:
The character should be given the configuration holotape at the moment it persist leaving v111.

Further Info:
Probably have to wait until the character is thawed as the loot obtained from v111 persists. Please add the necessary checks in dubhAutoLootQuest.pex

**Comment by fireundubh** [comment]
Thank you for the report. I'll look into this.

**Comment by fireundubh** [comment]
The holotape is now added to the player when the Pip-Boy is activated for the first time, or when the mod is first loaded any time after that point. This issue is now resolved. Please update to the latest version.
