### ISSUE TITLE
Auto-loot does not loot flora in unfiltered mode.

### ISSUE THREAD

**Issue by clampi** [fireundubh/fo4-mods#7]
While it is documented that it does not work, it would be a nice feature to have. It would be nicer if would pick-up loose items when in unfiltered mode, with let's say fireundubh personal hand-picked items, put somewhere in an editable FLST, so it can be extended such that will meet other person requirements.

**Comment by fireundubh** [comment]
Are you using the latest version? Filter Mode is off by default, and flora is most certainly auto looted. In a previous version, there was no option to turn Filter mode on or off on Page 2, so Page 1 modules were excluded when anything on Page 2 was enabled. But that hasn't been the case for awhile.

**Comment by clampi** [comment]
I am using the latest version on a brand new game.

Maybe the words filter and module aren't used consistently across the mod, but here is how it works.

- By default (brand new game) it doesn't loot anything.
Once I magically add the item through the console
- I load the holo-configurator, Page 2 ->activate corpses and containers. Now it starts to loot something. But not loose items nor flora.
- I load the holo-configurator again, Page 2 ->activate filter module. Page 1->activate flora module (should be named otherwise, to avoid confusion, but that's another subject)
Now it loots flora.
Above behavior is one tested with current version and latest beta patch of game, in a brad new game. So. from my perspective is not working.

**Comment by fireundubh** [comment]
> I load the holo-configurator, Page 2 ->activate corpses and containers. Now it starts to loot something. But not loose items nor flora.

Why would you expect loose items and flora to be looted? You didn't turn those modules on!

- If you want to auto loot flora, turn on the Flora Module.
- If you want to auto loot bodies, turn on the Bodies Module.
- If you want to auto loot flora and only junk in bodies, turn on the Flora Module, Junk Module, Filter Mode, and the Bodies Module.

**Comment by clampi** [comment]
I did not expect, I wish it had. Let me explain what I understood from the description.
The mod has 3 operating modes:
1) Off, default
2) Loot everything (only from corpses and containers) if those modules are enabled in page 2 of the holo-config. In this operating mode it won't loot flora nor loose items.
3) Filtered mode, once filter module is enabled in page 2, and it should be told what to filter-in. My understanding was that this operation mode applies to every location to be looted, container, corpse or loose item. Though one must still enable the corpse and container module so the items are looted from there also.
Also. it is stated in the page 1 that the settings there are only applied once filtered mode is on. So my understanding is that any filter-in option works only when the mod is put in filtering operating mode.

Now that I written the above, a less confusing way to think about is to explain/configure like this:
1) From where the loot is taken: container, corpses, loose items. flora, other activators
2) Which loot is taken.

I understand the limitation on working with VMAD and Fo4Edit, this is probably the cause to structure the menu the way it is structured now. A less confusing way, for me at least, would be like the one described above, maybe once GECK is published.

**Comment by fireundubh** [comment]
> maybe once GECK is published.

I wish people would stop saying this. Nearly everything that can be done with the CK can be done right now.

For Skyrim, I created all of my mods with only xEdit, including [Master of Disguise](http://www.gamespot.com/videos/top-5-skyrim-mods-of-the-week-become-the-master-of/2300-6423174/).

> Let me explain what I understood from the description.

1. Auto Loot defaults to off.
2. On Page 1, you can turn on auto loot modules for world objects (i.e., loose items.)
3. On Page 2, you can turn on auto loot modules for bodies and containers.

By default, the bodies and containers modules will transfer everything from bodies and containers to your inventory.

However, also on Page 2, you can toggle Filter Mode for only the bodies and containers modules.

* When Filter Mode is activated, the Page 1 Modules will continue to loot world objects.
* When Filter Mode is activated, the Page 1 Modules will pull double duty as filters for the bodies and containers modules.
* Flora cannot appear on bodies or containers, so Filter Mode is completely irrelevant to the flora module.

Example: If you're interested in only Junk, you'd activate the Junk module, the Bodies module, the Containers module, and Filter Mode. Auto Loot would then transfer Junk items in the open world, Junk items on bodies, and Junk items in containers to your inventory.
