### ISSUE TITLE
Scrap What You Make disables the option to move items that character can create

### ISSUE THREAD

**Issue by clampi** [fireundubh/fo4-mods#8]
This is experimented on a brand new game, with latest F4 beta patch and your latest version of the mod. It is extremely inconvenient as one has to move the created items because most of the times it won't be created in the final place it should be due to snapping issues. Please see the attached screenshots.

![vanilla](https://cloud.githubusercontent.com/assets/10470629/12639886/a3cb8d7e-c5af-11e5-965e-338b13b86781.png)
![withscrapwhatyoumake](https://cloud.githubusercontent.com/assets/10470629/12639895/b1654088-c5af-11e5-99e3-6ced11af988b.png)

It would be nice if a workaround would be found. Should be documented at least in the description page.

**Comment by fireundubh** [comment]
This is unrelated to Scrap What You Make. This mod does not override any records.

I'm more inclined to fault the recent patch, as I can no longer select and move the Chemistry Station in Sanctuary Hills.

**Comment by clampi** [comment]
There is a conflict between a normal workshop-build action and a "Scrap" only action (in COBJ) that prevents the moving option. I goggled a bit about the issue and found the solution applied here (in a similar context) http://www.nexusmods.com/fallout4/mods/4397/?. There, for planters to be movable, the Scrap-COBJ had to be deleted.

However, although this is certain to happen, the cause is not known and apart from deleting the Scrap-COBJ there is no known workaround. So in essence, this is a drawback of how this mod was implemented. IMHO it should be documented as such in the description page so others don't spend time repeating my investigation.

**Comment by fireundubh** [comment]
> So in essence, this is a drawback of how this mod was implemented.

I've implemented new scrap recipes that look just like Bethesda's scrap recipes in every respect. There are so few elements needed to create a scrap recipe that it is virtually impossible to go wrong. If there is a problem, it is not of my making.
